# Generated by Django 4.2.6 on 2023-10-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Upset', 'Upset'), ('Anxious', 'Anxious'), ('Sad', 'Sad'), ('Neutral', 'Neutral')], max_length=20),
        ),
    ]
